#requires -Version 7.0
<#
.SYNOPSIS
    Authority command surface: read-only status plus the reviewed transitions.

.DESCRIPTION
    `status` is strictly read-only: it resolves the authority context, validates
    the immutable claims and the schema 3 state, inspects the verified old lock
    and the live roots, scans the live-transaction namespace for unfinished
    journals, and prints exactly one route with its recommended next operation.

    The four transitions (`migrate`, `adopt`, `repair-adopt`, `takeover`) are
    plan producers. DryRun creates a new external plan bound to the exact
    context it validated - including a create-new environment materialization for
    the transitions that establish or repair a selection - and Apply consumes
    that exact existing plan: it re-validates the path, the envelope hashes, the
    materialization currency, the selection context, and the document's
    consumption state before anything else. Production Apply stays interlocked;
    outside the approved internal sandbox the interlock refuses the mutation
    with `safety-protocol-upgrade-required`.

    Operation kinds, requested-root contexts, and plans are not interchangeable:
    the requested action must equal the single route the read-only assessment
    emits, and Apply rejects a plan whose OperationKind differs from the action.

.PARAMETER Action
    status | migrate | adopt | repair-adopt | takeover.

.PARAMETER Name
    The environment name (bare identifier) for a transition. Migrate must pass
    the name recorded by the validated legacy state.

.PARAMETER LegacyStatePath
    Migrate only: the exact repo-local legacy state locator. Both invocations
    must pass the same path.

.PARAMETER CorruptStatePath
    Repair-adopt only, and only for the CORRUPT state-evidence branch: the exact
    authority schema 3 state path.

.PARAMETER ReasonixLiveSkillsPath
    Migrate/adopt only: the intended custom Reasonix live root, legal only while
    no schema 3 claims exist. Once claims exist the immutable claim is the only
    selector.

.PARAMETER DryRun
    Create a new external plan at -PlanPath. Never regenerated by Apply.

.PARAMETER Apply
    Consume the exact existing plan at -PlanPath.

.PARAMETER PlanPath
    External plan path (outside the worktree, Git internals, and safety roots).

.OUTPUTS
    Human-readable status or plan summary. Exit 0 on success.
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory)] [ValidateSet('status', 'migrate', 'adopt', 'repair-adopt', 'takeover')] [string] $Action,
    [string] $Name,
    [string] $LegacyStatePath,
    [string] $CorruptStatePath,
    [string] $ReasonixLiveSkillsPath,
    [string] $PlanPath,
    [switch] $DryRun,
    [switch] $Apply,
    [string] $RepoRoot = (Join-Path $PSScriptRoot '..'),
    [string] $HomeRoot,
    [string] $ControlBase,
    [string] $BackupRoot
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

. (Join-Path $PSScriptRoot 'live-plan-common.ps1')
. (Join-Path $PSScriptRoot 'live-plan-evidence-common.ps1')
. (Join-Path $PSScriptRoot 'harness-authority-status-common.ps1')
. (Join-Path $PSScriptRoot 'canonical-transaction-common.ps1')
. (Join-Path $PSScriptRoot 'live-transaction-common.ps1')

$script:AuthorityRouteMismatch = 'authority-route-mismatch'
$script:AuthorityNameRequired = 'authority-name-required'
$script:AuthorityPlanPathRequired = 'authority-plan-path-required'
$script:AuthorityLegacyLocatorRequired = 'authority-legacy-locator-required'
$script:AuthorityLegacyLocatorMismatch = 'authority-legacy-locator-mismatch'
$script:AuthorityLegacyNameMismatch = 'authority-legacy-name-mismatch'
$script:AuthorityStateEvidenceRequired = 'authority-state-evidence-required'
$script:AuthorityStateEvidenceForbidden = 'authority-state-evidence-forbidden'
$script:AuthorityArgumentUnsupported = 'authority-argument-unsupported'
$script:AuthorityPlanKindMismatch = 'authority-plan-kind-mismatch'
$script:AuthorityApplyNotWired = 'authority-apply-not-wired'
$script:AuthorityGeneratorName = 'scripts/authority-harness-env.ps1'

function Assert-AuthorityTransitionArguments {
    param([Parameter(Mandatory)] [string] $Action)

    if ($DryRun -and $Apply) { throw 'Specify -DryRun or -Apply, not both.' }
    if ([string]::IsNullOrWhiteSpace($Name)) { throw $script:AuthorityNameRequired }
    if ([string]::IsNullOrWhiteSpace($PlanPath)) { throw $script:AuthorityPlanPathRequired }
    if ($Action -cne 'migrate' -and -not [string]::IsNullOrWhiteSpace($LegacyStatePath)) { throw "$($script:AuthorityArgumentUnsupported): -LegacyStatePath is migrate-only." }
    if ($Action -cne 'repair-adopt' -and -not [string]::IsNullOrWhiteSpace($CorruptStatePath)) { throw "$($script:AuthorityArgumentUnsupported): -CorruptStatePath is repair-adopt-only." }
    if ($Action -cin @('repair-adopt', 'takeover') -and -not [string]::IsNullOrWhiteSpace($ReasonixLiveSkillsPath)) {
        throw "$($script:AuthorityArgumentUnsupported): -ReasonixLiveSkillsPath is not accepted by $Action."
    }
}

function Get-AuthorityIntendedReasonixRoot {
    # The optional custom root is legal only before the first authority exists;
    # afterwards the immutable claim is the only selector.
    param(
        [Parameter(Mandatory)] [System.Collections.IDictionary] $ClaimsDocument,
        [AllowNull()] [string] $Requested
    )

    if (-not [string]::IsNullOrWhiteSpace($Requested)) { return $Requested }
    $reasonix = @($ClaimsDocument.LiveRootClaims | Where-Object { [string] $_.Platform -ceq 'Reasonix' })
    if ($reasonix.Count -ne 1) { throw $script:AuthorityRouteMismatch }
    return [string] $reasonix[0].RequestedPath
}

$repo = (Resolve-Path -LiteralPath $RepoRoot).Path

# ---------------------------------------------------------------------------
# status: strictly read-only

if ($Action -ceq 'status') {
    if ($DryRun -or $Apply) { throw 'The authority status action accepts neither -DryRun nor -Apply.' }
    if (-not [string]::IsNullOrWhiteSpace($PlanPath) -or -not [string]::IsNullOrWhiteSpace($Name)) {
        throw "$($script:AuthorityArgumentUnsupported): status accepts neither -Name nor -PlanPath."
    }
    if (-not [string]::IsNullOrWhiteSpace($LegacyStatePath) -or -not [string]::IsNullOrWhiteSpace($CorruptStatePath)) {
        throw "$($script:AuthorityArgumentUnsupported): status accepts no transition evidence switches."
    }
    $assessment = Get-HarnessEnvAuthorityAssessment -RepoRoot $repo -ReasonixLiveSkillsPath $ReasonixLiveSkillsPath
    $controllerLabel = if ($null -eq $assessment.ControllerMatch) { 'not-applicable' } elseif ([bool] $assessment.ControllerMatch) { 'current' } else { 'foreign' }
    Write-Output "Authority route: $($assessment.Route)"
    Write-Output "  next operation: $($assessment.NextOperation)"
    Write-Output "  home authority: $($assessment.HomeAuthorityKeyLabel); controller: $controllerLabel"
    Write-Output "  claims: $($assessment.RootClaimsStatus); state: $($assessment.StateStatus); pair: $($assessment.PairStatus)"
    $recoveryDetail = if (@($assessment.UnfinishedTransactionIds).Count -gt 0) { " ($(@($assessment.UnfinishedTransactionIds) -join ', '))" } else { '' }
    Write-Output "  recovery: $($assessment.RecoveryStatus)$recoveryDetail"
    Write-Output "  legacy: $($assessment.Legacy.Status); gap: $($assessment.Legacy.Gap); old lock: $($assessment.Legacy.OldLockStatus); legacy parity: $($assessment.Legacy.LiveParity.Status)"
    Write-Output "  lock parity: $($assessment.LockParity.Status); live roots pristine: $($assessment.LiveRoots.Pristine); codex .system: $($assessment.SystemStatus)"
    if ($null -ne $assessment.IntendedRoot) {
        $label = if ($assessment.IntendedRoot.Contains('RequestedReasonixRoot')) { " ($($assessment.IntendedRoot.RequestedReasonixRoot))" } else { '' }
        Write-Output "  intended Reasonix root: $($assessment.IntendedRoot.Selection)$label; $($assessment.IntendedRoot.FilesystemCapabilityStatus); hash $($assessment.IntendedRoot.RequestedInitialRootContextHash)"
    }
    if ($null -ne $assessment.StateSummary) {
        Write-Output "  selection: $($assessment.StateSummary.EnvironmentName); generation $($assessment.StateSummary.AuthorityGeneration); last operation $($assessment.StateSummary.LastOperationKind)"
    }
    exit 0
}

# ---------------------------------------------------------------------------
# transitions: sandbox-resolved context, plan producer, apply gates

if (-not $DryRun -and -not $Apply) { throw 'The authority transition requires an explicit -DryRun or -Apply mode. Run -DryRun first.' }
Assert-AuthorityTransitionArguments -Action $Action
$null = Get-HarnessEnvStagingRoot -RepoRoot $repo -Name $Name
$planFull = [System.IO.Path]::GetFullPath($PlanPath)
# The CLI action names its route; the frozen plan operation kind for a
# controller takeover is `controller-transition`.
$operationKind = if ($Action -ceq 'takeover') { 'controller-transition' } else { $Action }

if ($Apply) {
    # The production interlock is the first gate on the mutation path: outside
    # the approved internal sandbox it refuses with the policy token before any
    # traversal, plan consumption, or host composition.
    $interlockPaths = @($repo, $ReasonixLiveSkillsPath, $planFull, $HomeRoot, $ControlBase, $BackupRoot) |
        Where-Object { -not [string]::IsNullOrWhiteSpace([string] $_) } |
        ForEach-Object { [System.IO.Path]::GetFullPath([string] $_) }
    Assert-LiveSafetyMutationAllowed -Operation "authority-$Action" -Paths @($interlockPaths)
    $null = Resolve-PrivateArtifactPath -Path $planFull -Role ExternalUserArtifact -RepoRoot $repo
    $readDocument = Read-LiveSyncPlan -Path $planFull
    Assert-LiveSyncPlanDocumentIntegrity -Document $readDocument
    if ([string] $readDocument.PlanPayload.OperationKind -cne $operationKind) { throw $script:AuthorityPlanKindMismatch }
    if ($readDocument.PlanPayload.Contains('EnvironmentMaterializationRoot')) {
        $null = Assert-LiveSyncPlanCurrent -Document $readDocument -MaterializationDirectory ([string] $readDocument.PlanPayload.EnvironmentMaterializationRoot.Path)
    }
    $null = Assert-LiveSyncPlanSelectionContext -Document $readDocument -ExpectedOperationKind $operationKind -ExpectedEnvironmentName $Name
    Assert-LiveSyncPlanDocumentHashNotConsumed -Document $readDocument
    throw "$($script:AuthorityApplyNotWired): the reviewed apply composition for '$Action' is delivered by the Task 4/5 slices."
}

if (Test-Path -LiteralPath $planFull) { throw $script:LivePlanPathCollision }
$null = Resolve-PrivateArtifactPath -Path $planFull -Role ExternalUserArtifact -RepoRoot $repo -AllowMissingLeaf

if ([string]::IsNullOrWhiteSpace($HomeRoot) -or [string]::IsNullOrWhiteSpace($ControlBase) -or [string]::IsNullOrWhiteSpace($BackupRoot)) {
    $internalRoots = Resolve-LiveSyncInternalRoots
    $HomeRoot = [string] $internalRoots.HomeRoot
    $ControlBase = [string] $internalRoots.ControlBase
    $BackupRoot = [string] $internalRoots.BackupRoot
}
$HomeRoot = [System.IO.Path]::GetFullPath($HomeRoot)
$ControlBase = [System.IO.Path]::GetFullPath($ControlBase)
$BackupRoot = [System.IO.Path]::GetFullPath($BackupRoot)
$RepoRoot = $repo
$authorityIdentity = [pscustomobject][ordered]@{
    ResolverVersion = $script:HomeAuthorityResolverVersion
    TokenSid = [System.Security.Principal.WindowsIdentity]::GetCurrent().User.Value
    ProfileRoot = [System.IO.Path]::GetFullPath($HomeRoot)
    RoamingAppDataRoot = (Join-Path ([System.IO.Path]::GetFullPath($HomeRoot)) 'AppData\Roaming')
    LocalAppDataRoot = (Join-Path ([System.IO.Path]::GetFullPath($HomeRoot)) 'AppData\Local')
}
$authorityContext = New-LiveSyncAuthorityContext -HomeRoot $HomeRoot -ControlBase $ControlBase -BackupRoot $BackupRoot
$assessment = Get-HarnessEnvAuthorityAssessment -RepoRoot $repo -Identity $authorityIdentity -ReasonixLiveSkillsPath $ReasonixLiveSkillsPath
if ([string] $assessment.Route -cne $Action) { throw "$($script:AuthorityRouteMismatch): the read-only assessment routes to '$($assessment.Route)', not '$Action'." }

$authorityState = Read-HomeAuthorityState -ControlBase ([string] $authorityContext.ControlBase) -HomeAuthorityKey ([string] $authorityContext.HomeAuthorityKey) -RepoRoot $repo

# ---------------------------------------------------------------------------
# Operation-specific context binding

$legacyAssessment = $null
$legacyCoreHash = $null
$oldLockHash = $null
$stateEvidence = $null
$legacyEvidence = $null
$controllerParity = $null
$tokenSid = [string] $authorityContext.TokenSid

switch ($Action) {
    'migrate' {
        if ([string]::IsNullOrWhiteSpace($LegacyStatePath)) { throw $script:AuthorityLegacyLocatorRequired }
        $expectedLegacyPath = [System.IO.Path]::GetFullPath((Get-HarnessEnvStatePath -RepoRoot $repo))
        if ([System.IO.Path]::GetFullPath($LegacyStatePath) -cne $expectedLegacyPath) { throw $script:AuthorityLegacyLocatorMismatch }
        $legacy = Read-LegacyHarnessEnvState -RepoRoot $repo
        if ([string] $legacy.Status -cne 'VALID') { throw $script:LivePlanSelectionMismatch }
        $legacyDocument = [System.Collections.IDictionary] $legacy.Document
        if ([string] $legacyDocument['Name'] -ine $Name) { throw $script:AuthorityLegacyNameMismatch }
        $legacyCoreHash = Get-HarnessLegacyEnvCoreHash -Document $legacyDocument
        $oldLockPath = Join-Path (Join-Path $repo 'envs') (Join-Path $Name 'env.lock.json')
        if (-not (Test-Path -LiteralPath $oldLockPath -PathType Leaf)) { throw $script:LivePlanSelectionMismatch }
        $oldLockHash = (Get-HarnessFileHash -Path $oldLockPath).ToLowerInvariant()
        $legacyAssessment = @{ LegacyHash = [string] $legacy.BytesHash; LegacyLocator = $expectedLegacyPath }
    }
    'adopt' {
        $legacyStatus = [string] $assessment.Legacy.Status
        if ($legacyStatus -cnotin @('MISSING', 'UNTRUSTED', 'CORRUPT')) { throw $script:LivePlanSelectionMismatch }
        $legacyEvidence = [ordered] @{ Status = $(if ($legacyStatus -ceq 'MISSING') { 'MISSING' } else { 'UNTRUSTED' }) }
    }
    'repair-adopt' {
        if ([string] $authorityState.ClaimsStatus -cne 'VALID') { throw $script:LivePlanSelectionMismatch }
        $stateStatusForEvidence = [string] $authorityState.StateStatus
        if ($stateStatusForEvidence -ceq 'CORRUPT') {
            if ([string]::IsNullOrWhiteSpace($CorruptStatePath)) { throw $script:AuthorityStateEvidenceRequired }
            $expectedStatePath = [System.IO.Path]::GetFullPath([string] $authorityContext.CurrentEnvStatePath)
            if ([System.IO.Path]::GetFullPath($CorruptStatePath) -cne $expectedStatePath) { throw $script:LivePlanSelectionMismatch }
            if (-not (Test-Path -LiteralPath $expectedStatePath -PathType Leaf)) { throw $script:LivePlanSelectionMismatch }
            $stateBytes = [System.IO.File]::ReadAllBytes($expectedStatePath)
            # Both hashes cover the exact kept bytes: RawHash identifies the
            # corrupt evidence, PreimageHash the durable preimage the apply
            # composition journals before it replaces the state.
            $stateBytesHash = Get-BytesSha256 -Bytes $stateBytes
            $stateEvidence = [ordered] @{
                Kind = 'CORRUPT'
                Path = $expectedStatePath
                RawHash = $stateBytesHash
                PreimageHash = $stateBytesHash
            }
        }
        elseif ($stateStatusForEvidence -ceq 'MISSING') {
            if (-not [string]::IsNullOrWhiteSpace($CorruptStatePath)) { throw $script:AuthorityStateEvidenceForbidden }
            $stateEvidence = [ordered] @{ Kind = 'MISSING'; Marker = $true }
        }
        else {
            throw $script:LivePlanSelectionMismatch
        }
    }
    'takeover' {
        if ([string] $authorityState.PairStatus -cne 'VALID') { throw $script:LivePlanSelectionMismatch }
        $currentController = Get-CanonicalRepoIdentity -GitContext (Get-CanonicalGitContext -RepoRoot $repo)
        $controllerParity = [ordered] @{ PreviousControllerRepoFingerprint = [string] $authorityState.StateDocument['ControllerRepoFingerprint'] }
        if ([string] $controllerParity.PreviousControllerRepoFingerprint -ceq $currentController) { throw $script:AuthorityRouteMismatch }
    }
}

# ---------------------------------------------------------------------------
# Plan assembly (mirrors the reviewed initial producer; branch evidence differs)

$git = Get-CanonicalGitContext -RepoRoot $repo
$controllerFingerprint = Get-CanonicalRepoIdentity -GitContext $git
$toolchainHash = Get-LiveSyncApprovedToolchainHash -RepoRoot $repo
$homeContext = Get-LiveSyncTargetContext -Path ([System.IO.Path]::GetFullPath($authorityContext.HomeRoot))
$homeAuthorityKey = [string] $authorityContext.HomeAuthorityKey
$controlContext = Get-LiveSyncTargetContext -Path ([System.IO.Path]::GetFullPath($ControlBase))

$managedNames = [ordered]@{
    Claude = (Read-ManagedNames -Path (Join-Path $repo 'manifests\managed-skills.claude.txt'))
    Codex = (Read-ManagedNames -Path (Join-Path $repo 'manifests\managed-skills.codex.txt'))
    Reasonix = (Read-ManagedNames -Path (Join-Path $repo 'manifests\managed-skills.reasonix.txt'))
}
$manifestHashes = [ordered]@{
    Claude = (Get-PathSha256 -Path (Join-Path $repo 'manifests\managed-skills.claude.txt'))
    Codex = (Get-PathSha256 -Path (Join-Path $repo 'manifests\managed-skills.codex.txt'))
    Reasonix = (Get-PathSha256 -Path (Join-Path $repo 'manifests\managed-skills.reasonix.txt'))
}

$materialization = $null
$liveRootsByPlatform = [ordered] @{
    Claude = (Get-ClaudeLiveSkillsPath)
    Codex = (Get-CodexLiveSkillsPath)
    Reasonix = (Get-ReasonixLiveSkillsPath)
}
if ($Action -cne 'takeover') {
    # The claim (existing authority) or the intended selection (first authority)
    # is the only live-root selector; the platform defaults are never assumed
    # once an authority exists.
    if ([string] $authorityState.PairStatus -ceq 'VALID') {
        foreach ($identity in @($authorityState.StateDocument['FinalResolvedIdentities'])) {
            $liveRootsByPlatform[[string] $identity.Platform] = [string] $identity.ResolvedPath
        }
    }
    elseif (-not [string]::IsNullOrWhiteSpace($ReasonixLiveSkillsPath)) {
        $liveRootsByPlatform.Reasonix = [System.IO.Path]::GetFullPath($ReasonixLiveSkillsPath)
    }
}

$claims = [System.Collections.Generic.List[object]]::new()
$claimsDocument = $null
$claimsHash = $null
if ([string] $authorityState.PairStatus -ceq 'VALID') {
    $claimsDocument = $authorityState.ClaimsDocument
    $claimsHash = [string] $authorityState.ClaimsBytesHash
}
else {
    foreach ($platform in @('Claude', 'Codex', 'Reasonix')) {
        $liveContext = Get-LiveSyncTargetContext -Path ([System.IO.Path]::GetFullPath([string] $liveRootsByPlatform[$platform]))
        $initialState = if ([string] $liveContext.TargetStatus -ceq 'EXISTS') { 'EXISTS' } else { 'ABSENT' }
        $claims.Add((New-LiveSyncRootClaimRow -Platform $platform -Context $liveContext -InitialState $initialState))
    }
    $claimsDocument = [ordered]@{
        SchemaVersion = 1
        ArtifactKind = 'root-claims'
        HomeAuthorityKey = $homeAuthorityKey
        TokenSid = $tokenSid
        ResolverVersion = $script:HomeAuthorityResolverVersion
        HomeRootLocationKey = [string] $homeContext.LocationKey
        LiveRootClaims = @($claims)
    }
    $claimsBytes = [byte[]] (ConvertTo-SemanticJsonBytes -InputObject $claimsDocument)
    $claimsHash = [Convert]::ToHexString([Security.Cryptography.SHA256]::HashData($claimsBytes)).ToLowerInvariant()
}

$intendedReasonixRoot = Get-AuthorityIntendedReasonixRoot -ClaimsDocument $claimsDocument -Requested $ReasonixLiveSkillsPath

$orderedActions = [System.Collections.Generic.List[object]]::new()
$slots = [System.Collections.Generic.List[object]]::new()
$materializationRoot = $null
$unknownMarkers = [System.Collections.Generic.List[object]]::new()
$intent = $null
if ($Action -cne 'takeover') {
    $materializationPath = Get-LiveSyncMaterializationPath -PlanPath $planFull
    $materialization = New-LiveSyncMaterializationEvidence -MaterializationPath $materializationPath -RepoRoot $repo -Name $Name
    $build = [System.Collections.IDictionary] $materialization['Build']

    $order = 0L
    foreach ($platform in @('Claude', 'Codex', 'Reasonix')) {
        $key = $platform.ToLowerInvariant()
        $stagedHashes = [System.Collections.IDictionary] (Get-HarnessJsonProperty -Object (Get-HarnessJsonProperty -Object $build -Name 'StagedSkillTreeHashes') -Name $platform)
        $stagedSourceBase = Join-Path ([string] $materialization['Path']) "$key/skills"
        foreach ($skillName in (@([string[]] $stagedHashes.Keys) | Sort-Object { [string] $_ })) {
            $sourceHash = [string] (Get-SafeTreeSnapshot -Root (Join-Path $stagedSourceBase $skillName)).TreeHash
            if ($sourceHash -cnotmatch '\A[0-9a-f]{64}\z') { throw $script:LiveSyncUnsupportedApplyKind }
            $orderedActions.Add([ordered]@{
                Order = $order
                Platform = $platform
                Action = 'add'
                Name = $skillName
                SourceHash = $sourceHash
                LiveHash = $null
            })
            $order++
        }
        $slots.Add((New-LiveSyncPlatformSlot -Platform $platform -SourceRoot (Join-Path ([string] $materialization['Path']) "$key/skills") -LiveRoot ([string] $liveRootsByPlatform[$platform]) -ManagedNames $managedNames[$platform] -ManifestHash $manifestHashes[$platform]))
        foreach ($marker in @(Get-LiveSyncUnknownMarkers -Platform $platform -LiveRoot ([string] $liveRootsByPlatform[$platform]) -ManagedNames $managedNames[$platform])) {
            $unknownMarkers.Add($marker)
        }
    }
    $materializationRoot = [ordered]@{
        Path = [string] $materialization['Path']
        Identity = [string] $materialization['Identity']
        EnvBuildPath = [string] $materialization['EnvBuildPath']
        EnvBuildHash = [string] $materialization['EnvBuildHash']
        EnvLockPath = [string] $materialization['EnvLockPath']
        EnvLockHash = [string] $materialization['EnvLockHash']
        MaterializationHash = [string] $materialization['MaterializationHash']
    }

    $overlaySkillsRows = Get-LiveSyncPlatformTriple -Map (Get-HarnessJsonProperty -Object $build -Name 'TaskOverlaySkills') -Kind 'Skills'
    $intent = [ordered]@{
        SchemaVersion = 3
        ArtifactKind = 'current-env-state'
        HomeAuthorityKey = $homeAuthorityKey
        AuthorityGeneration = 1
        RootClaimsHash = $claimsHash
        SelectionKind = 'environment'
        EnvironmentName = $Name
        EnvironmentLockHash = [string] $materialization['EnvLockHash']
        TaskOverlayHash = (Get-LiveSyncTaskOverlayHash -OverlayHash ([string] (Get-HarnessJsonProperty -Object $build -Name 'TaskOverlayHash')) -TaskOverlaySkillsRows $overlaySkillsRows)
        TaskOverlaySkills = $overlaySkillsRows
        ManifestHashes = (Get-LiveSyncPlatformTriple -Map (Get-HarnessJsonProperty -Object $build -Name 'ManifestHashes') -Kind 'Hash')
        FinalManagedHashes = @(
            foreach ($platform in @('Claude', 'Codex', 'Reasonix')) {
                [ordered]@{
                    Platform = $platform
                    Hash = [string] (Get-HarnessJsonProperty -Object (Get-HarnessJsonProperty -Object (Get-HarnessJsonProperty -Object $build -Name 'MaterializedRoots') -Name $platform) -Name 'TreeHash')
                }
            }
        )
        ControllerRepoFingerprint = $controllerFingerprint
        ApprovedToolchainHash = $toolchainHash
        LastOperationKind = $operationKind
    }
}
else {
    # A controller transition mutates no live content: the platform slots bind
    # the current live roots as their own source (equal tree hashes, zero
    # actions), which is exactly the state-only contract.
    foreach ($platform in @('Claude', 'Codex', 'Reasonix')) {
        $platformLiveRoot = [string] $liveRootsByPlatform[$platform]
        $slots.Add((New-LiveSyncPlatformSlot -Platform $platform -SourceRoot $platformLiveRoot -LiveRoot $platformLiveRoot -ManagedNames $managedNames[$platform] -ManifestHash $manifestHashes[$platform]))
        foreach ($marker in @(Get-LiveSyncUnknownMarkers -Platform $platform -LiveRoot $platformLiveRoot -ManagedNames $managedNames[$platform])) {
            $unknownMarkers.Add($marker)
        }
    }
    $intent = [ordered]@{
        SchemaVersion = 3
        ArtifactKind = 'current-env-state'
        HomeAuthorityKey = $homeAuthorityKey
        AuthorityGeneration = ([long] $authorityState.StateDocument['AuthorityGeneration'] + 1)
        RootClaimsHash = [string] $authorityState.ClaimsBytesHash
        SelectionKind = 'environment'
        EnvironmentName = [string] $authorityState.StateDocument['EnvironmentName']
        EnvironmentLockHash = [string] $authorityState.StateDocument['EnvironmentLockHash']
        TaskOverlayHash = [string] $authorityState.StateDocument['TaskOverlayHash']
        TaskOverlaySkills = @(Get-HarnessJsonProperty -Object $authorityState.StateDocument -Name 'TaskOverlaySkills')
        ManifestHashes = @(Get-HarnessJsonProperty -Object $authorityState.StateDocument -Name 'ManifestHashes')
        FinalManagedHashes = @(Get-HarnessJsonProperty -Object $authorityState.StateDocument -Name 'FinalManagedHashes')
        ControllerRepoFingerprint = $controllerFingerprint
        ApprovedToolchainHash = $toolchainHash
        LastOperationKind = 'controller-transition'
        ReceiptRef = 'NO_LIVE_MUTATION'
    }
}

$systemMarker = Get-LiveSyncSystemMarker -CodexLiveRoot ([string] $liveRootsByPlatform.Codex)

$payload = [ordered]@{
    OperationKind = $operationKind
    Generator = $script:AuthorityGeneratorName
    RepositoryCommit = [string] $git.RepositoryCommit
    RepoRoot = $repo
    ApprovedToolchainHash = $toolchainHash
    ControllerRepoFingerprint = $controllerFingerprint
    ControlBaseIntent = (New-LiveSyncControlBaseIntent -Context $controlContext)
    Platforms = @($slots)
    OrderedActions = @($orderedActions)
    UnknownMarkers = @($unknownMarkers)
    SystemMarker = $systemMarker
    TargetContextIntent = [ordered]@{ HomeAuthorityKey = $homeAuthorityKey; Rows = @($claimsDocument.LiveRootClaims) }
    AuthorityStateIntent = $intent
}
if ($Action -cin @('migrate', 'adopt', 'repair-adopt')) {
    $payload['EnvironmentName'] = $Name
}
if ($Action -cin @('migrate', 'adopt', 'repair-adopt')) {
    $payload['EnvironmentMaterializationRoot'] = $materializationRoot
}
if ([string] $authorityState.PairStatus -cne 'VALID' -and $Action -cin @('migrate', 'adopt')) {
    $payload['ProposedRootClaims'] = $claimsDocument
    $payload['RootClaimsHash'] = $claimsHash
}
if ($Action -ceq 'migrate') {
    $payload['LegacyLocator'] = [string] $legacyAssessment.LegacyLocator
    $payload['LegacyHash'] = [string] $legacyAssessment.LegacyHash
    $payload['LegacyCoreHash'] = [string] $legacyCoreHash
    $payload['OldLockHash'] = [string] $oldLockHash
}
if ($Action -ceq 'adopt') { $payload['LegacyEvidence'] = $legacyEvidence }
if ($Action -ceq 'repair-adopt') { $payload['StateEvidence'] = $stateEvidence }
if ($Action -ceq 'takeover') { $payload['ControllerParity'] = $controllerParity }

$document = [ordered]@{
    SchemaVersion = 3
    ArtifactKind = 'sync-plan'
    Metadata = [ordered]@{ GeneratedAtUtc = [DateTime]::UtcNow.ToString('o') }
    PlanPayload = $payload
}
$document['PlanHash'] = Get-PlanHash -PlanPayload $payload
$document['DocumentHash'] = Get-DocumentHash -Document $document
Assert-LiveSyncPlanDocumentIntegrity -Document $document

Write-LiveSyncPlan -Path $planFull -Document $document
Write-PlanSummary -Payload $payload
Write-Host "Plan path       : $planFull"
Write-Host "Materialization : $(if ($null -ne $materializationRoot) { [string] $materializationRoot.Path } else { '<none>' })"

exit 0
